version: '1.0'
services:
  privategpt:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./workspace:/workspace
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              
